 variable env                        {}
 variable prefix                     {}
 variable vpc_id                     {}
 variable vpc_cidr                   {}
 variable cluster_subnets            {}
 variable worker_node_subnets        {}
 variable eks_cluster_name           {}
 variable eks_cluster_role           {}
 variable eks_cluster_version        {}
 variable eks_cluster_sg_id          {}
 variable eks_node_group_role        {}
 variable eks_node_type              {}
 variable ssh_key                    {}
 variable user_data                  {}
 variable eks_node_sg_id             {}
 variable desired_size               {}
 variable min_size                   {}
 variable max_size                   {}
